version: 4.0.1.{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - LLVM_4_0_1
skip_commits:
  files:
    - appveyor.yml
image: Visual Studio 2017
cache: BuildOutput\packages

nuget:
  disable_publish_on_pr: true
  account_feed: true
  project_feed: true

build:
  project: buildall.slnproj
  parallel: true
  verbosity: minimal

before_build:
  - ps: .\Update-AppveyorVersion.ps1
