version: 4.0.1.{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - LLVM_4_0_1

image: Visual Studio 2017

nuget:
  disable_publish_on_pr: true
  account_feed: false
  project_feed: false

build:
  project: buildall.slnproj
  parallel: true
  verbosity: minimal

build_script:
  - ps: .\BuildAll.ps1
