version: 4.0.1.{build}

pull_requests:
  do_not_increment_build_number: true

branches:
  only:
  - LLVM_4_0_1

image: Visual Studio 2017

skip_commits:
  files:
    - '**\*.md'

nuget:
  disable_publish_on_pr: true
  account_feed: true
  project_feed: true

build:
  parallel: true
  verbosity: minimal

build_script:
  - ps: .\BuildAll.ps1

artifacts:
  - path: .\BuildOutput\Nuget\*.nupkg
