version: 5.0.0.{build}

pull_requests:
  do_not_increment_build_number: true

branches:
  only:
  - Llvm.Libs

image: Visual Studio 2017

skip_commits:
  files:
    - '**\*.md'

environment:
  BuildNugetUser:
    secure: f6wD21gZoNIxzurB9sZmRKGWa9Dpj4BjUdPqOmj7WqM=
  BuildNugetPassword:
    secure: C4Z+91Dp0oltWIm1cjf5Lw==

platform:
  - x86
  - x64
  - AnyCPU

configuration:
  - Debug
  - Release

# Disable debug variant of AnyCPU as it has no meaning
# AnyCPU is used to build the Meta-Package that contains the headers along with the common props and targets files
matrix:
  exclude:
    - configuration: Debug
      platform: AnyCPU

nuget:
  disable_publish_on_pr: true
  account_feed: false
  project_feed: true

install:
  - ps: .\scripts\update.ps1

build_script:
  - ps: .\scripts\build-llvm.ps1 -Build -Platform $env:PLATFORM -Configuration $env:Configuration

artifacts:
  - path: pkginstall\**\Llvm.Libs.*.nupkg
