version: 4.0.1.{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - LLVM_4_0_1
skip_commits:
  files:
    - appveyor.yml
image: Visual Studio 2017
configuration:
  - Debug
  - Release
platform:
  - x86
  - x64
nuget:
  disable_publish_on_pr: true
build:
  project: buildall.slnproj
  parallel: true
  verbosity: minimal