version: 4.0.1.{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - LLVM_4_0_1

image: Visual Studio 2017

environment:
  BuildNugetUser:
    secure: f6wD21gZoNIxzurB9sZmRIG7am6l15frDAdL5FSYIvM=
  BuildNugetPassword:
    secure: C4Z+91Dp0oltWIm1cjf5Lw==

nuget:
  disable_publish_on_pr: true
  account_feed: true
  project_feed: true

install:
  - nuget source update -Name AppveyorAccountFeed -UserName %BuildNugetUser% -Password %BuildNugetPassword%
build:
  project: buildall.slnproj
  parallel: true
  verbosity: minimal

build_script:
  - ps: .\BuildAll.ps1
